// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemUznawaniaPrzychodow.Data;

#nullable disable

namespace SystemUznawaniaPrzychodow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614142930_ChangeEmployeeData")]
    partial class ChangeEmployeeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);

                    b.HasDiscriminator<string>("ClientType").HasValue("Client");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<int>("AdditionalSupportYears")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContractId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            ContractId = 1,
                            AdditionalSupportYears = 1,
                            ClientId = 1,
                            DateFrom = new DateOnly(2026, 1, 15),
                            DateTo = new DateOnly(2027, 1, 15),
                            Deadline = new DateOnly(2026, 1, 30),
                            IsSigned = true,
                            Price = 5000.00m,
                            SoftwareId = 1,
                            SoftwareVersion = "2026.1"
                        },
                        new
                        {
                            ContractId = 2,
                            AdditionalSupportYears = 0,
                            ClientId = 4,
                            DateFrom = new DateOnly(2026, 2, 10),
                            DateTo = new DateOnly(2027, 2, 10),
                            Deadline = new DateOnly(2026, 2, 25),
                            IsSigned = true,
                            Price = 8000.00m,
                            SoftwareId = 3,
                            SoftwareVersion = "11.0"
                        },
                        new
                        {
                            ContractId = 3,
                            AdditionalSupportYears = 2,
                            ClientId = 5,
                            DateFrom = new DateOnly(2026, 5, 1),
                            DateTo = new DateOnly(2027, 5, 1),
                            Deadline = new DateOnly(2026, 5, 15),
                            IsSigned = true,
                            Price = 3000.00m,
                            SoftwareId = 5,
                            SoftwareVersion = "2026.2"
                        },
                        new
                        {
                            ContractId = 4,
                            AdditionalSupportYears = 1,
                            ClientId = 2,
                            DateFrom = new DateOnly(2026, 7, 1),
                            DateTo = new DateOnly(2027, 7, 1),
                            Deadline = new DateOnly(2026, 7, 25),
                            IsSigned = false,
                            Price = 12000.00m,
                            SoftwareId = 1,
                            SoftwareVersion = "2026.1"
                        },
                        new
                        {
                            ContractId = 5,
                            AdditionalSupportYears = 0,
                            ClientId = 6,
                            DateFrom = new DateOnly(2026, 6, 20),
                            DateTo = new DateOnly(2027, 6, 20),
                            Deadline = new DateOnly(2026, 7, 8),
                            IsSigned = false,
                            Price = 4500.00m,
                            SoftwareId = 4,
                            SoftwareVersion = "2.5"
                        },
                        new
                        {
                            ContractId = 6,
                            AdditionalSupportYears = 3,
                            ClientId = 3,
                            DateFrom = new DateOnly(2026, 4, 1),
                            DateTo = new DateOnly(2027, 4, 1),
                            Deadline = new DateOnly(2026, 5, 1),
                            IsSigned = false,
                            Price = 3500.00m,
                            SoftwareId = 2,
                            SoftwareVersion = "4.2"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiscountId"));

                    b.Property<DateOnly>("DateFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateTo")
                        .HasColumnType("date");

                    b.Property<string>("DiscountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Offer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("DiscountId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Discounts", (string)null);

                    b.HasData(
                        new
                        {
                            DiscountId = 1,
                            DateFrom = new DateOnly(2026, 5, 1),
                            DateTo = new DateOnly(2026, 8, 31),
                            DiscountName = "Letnia Promocja ERP",
                            Offer = "Subscription",
                            Percentage = 10.00m,
                            SoftwareId = 1
                        },
                        new
                        {
                            DiscountId = 2,
                            DateFrom = new DateOnly(2025, 12, 1),
                            DateTo = new DateOnly(2026, 2, 28),
                            DiscountName = "Zimowa Promocja Edu",
                            Offer = "Contract",
                            Percentage = 15.00m,
                            SoftwareId = 2
                        },
                        new
                        {
                            DiscountId = 3,
                            DateFrom = new DateOnly(2026, 3, 1),
                            DateTo = new DateOnly(2026, 6, 30),
                            DiscountName = "Wiosenny CRM",
                            Offer = "Contract",
                            Percentage = 5.00m,
                            SoftwareId = 3
                        },
                        new
                        {
                            DiscountId = 4,
                            DateFrom = new DateOnly(2026, 1, 1),
                            DateTo = new DateOnly(2026, 12, 31),
                            DiscountName = "Cloud Start Bonus",
                            Offer = "Subscription",
                            Percentage = 20.00m,
                            SoftwareId = 4
                        },
                        new
                        {
                            DiscountId = 5,
                            DateFrom = new DateOnly(2026, 6, 1),
                            DateTo = new DateOnly(2026, 7, 15),
                            DiscountName = "HR New Release",
                            Offer = "Contract",
                            Percentage = 12.00m,
                            SoftwareId = 5
                        },
                        new
                        {
                            DiscountId = 6,
                            DateFrom = new DateOnly(2026, 6, 10),
                            DateTo = new DateOnly(2026, 6, 20),
                            DiscountName = "AI Launch Promo",
                            Offer = "Subscription",
                            Percentage = 25.00m,
                            SoftwareId = 6
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Login = "admin",
                            PasswordHash = "admin123",
                            Role = "Admin"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Login = "user",
                            PasswordHash = "user123",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.HasKey("PaymentId");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments", (string)null);

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 5000.00m,
                            ContractId = 1,
                            IsRefunded = false,
                            PaymentDate = new DateOnly(2026, 1, 20)
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 4000.00m,
                            ContractId = 2,
                            IsRefunded = false,
                            PaymentDate = new DateOnly(2026, 2, 15)
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 4000.00m,
                            ContractId = 2,
                            IsRefunded = false,
                            PaymentDate = new DateOnly(2026, 2, 20)
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 3000.00m,
                            ContractId = 3,
                            IsRefunded = false,
                            PaymentDate = new DateOnly(2026, 5, 5)
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 5000.00m,
                            ContractId = 1,
                            IsRefunded = true,
                            PaymentDate = new DateOnly(2026, 1, 21)
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 1500.00m,
                            ContractId = 3,
                            IsRefunded = true,
                            PaymentDate = new DateOnly(2026, 5, 6)
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Software", b =>
                {
                    b.Property<int>("SoftwareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareId"));

                    b.Property<decimal>("AnnualPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("SoftwareId");

                    b.ToTable("Software", (string)null);

                    b.HasData(
                        new
                        {
                            SoftwareId = 1,
                            AnnualPrice = 4999.99m,
                            Category = "Biznes",
                            Description = "Zarządzanie przedsiębiorstwem",
                            SoftwareName = "ERP System Pro",
                            Version = "2026.1"
                        },
                        new
                        {
                            SoftwareId = 2,
                            AnnualPrice = 1499.00m,
                            Category = "Edukacja",
                            Description = "Platforma e-learningowa",
                            SoftwareName = "EduLearn Platform",
                            Version = "4.2"
                        },
                        new
                        {
                            SoftwareId = 3,
                            AnnualPrice = 2999.50m,
                            Category = "Biznes",
                            Description = "System zarządzania relacjami",
                            SoftwareName = "SecureVault CRM",
                            Version = "11.0"
                        },
                        new
                        {
                            SoftwareId = 4,
                            AnnualPrice = 899.00m,
                            Category = "Narzędzia",
                            Description = "Chmura dla firm",
                            SoftwareName = "CloudDrive Core",
                            Version = "2.5"
                        },
                        new
                        {
                            SoftwareId = 5,
                            AnnualPrice = 2450.00m,
                            Category = "HR",
                            Description = "Automatyzacja procesów HR",
                            SoftwareName = "HR Automate",
                            Version = "2026.2"
                        },
                        new
                        {
                            SoftwareId = 6,
                            AnnualPrice = 7900.00m,
                            Category = "Finanse",
                            Description = "Analityka finansowa AI",
                            SoftwareName = "FinAnalyse Premium",
                            Version = "1.0"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("RenewalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RenewalPeriod")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ClientId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Subscriptions", (string)null);

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            ClientId = 1,
                            IsActive = true,
                            RenewalAmount = 200.00m,
                            RenewalPeriod = 1,
                            SoftwareId = 2,
                            StartDate = new DateOnly(2026, 4, 15),
                            SubscriptionName = "EduLearn Premium"
                        },
                        new
                        {
                            SubscriptionId = 2,
                            ClientId = 3,
                            IsActive = true,
                            RenewalAmount = 500.00m,
                            RenewalPeriod = 1,
                            SoftwareId = 4,
                            StartDate = new DateOnly(2026, 5, 1),
                            SubscriptionName = "CloudDrive Business"
                        },
                        new
                        {
                            SubscriptionId = 3,
                            ClientId = 4,
                            IsActive = true,
                            RenewalAmount = 1500.00m,
                            RenewalPeriod = 3,
                            SoftwareId = 6,
                            StartDate = new DateOnly(2026, 6, 11),
                            SubscriptionName = "FinAnalyse Enterprise"
                        },
                        new
                        {
                            SubscriptionId = 4,
                            ClientId = 5,
                            IsActive = true,
                            RenewalAmount = 300.00m,
                            RenewalPeriod = 1,
                            SoftwareId = 1,
                            StartDate = new DateOnly(2026, 3, 10),
                            SubscriptionName = "ERP Lite Client"
                        },
                        new
                        {
                            SubscriptionId = 5,
                            ClientId = 2,
                            IsActive = false,
                            RenewalAmount = 450.00m,
                            RenewalPeriod = 3,
                            SoftwareId = 2,
                            StartDate = new DateOnly(2025, 9, 1),
                            SubscriptionName = "EduLearn Basic"
                        },
                        new
                        {
                            SubscriptionId = 6,
                            ClientId = 6,
                            IsActive = false,
                            RenewalAmount = 100.00m,
                            RenewalPeriod = 1,
                            SoftwareId = 3,
                            StartDate = new DateOnly(2026, 1, 1),
                            SubscriptionName = "SecureVault Promo"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.SubscriptionRenewal", b =>
                {
                    b.Property<int>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("RenewalId");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionRenewals", (string)null);

                    b.HasData(
                        new
                        {
                            RenewalId = 1,
                            AmountPaid = 190.00m,
                            PaymentDate = new DateOnly(2026, 4, 15),
                            PeriodEnd = new DateOnly(2026, 5, 15),
                            PeriodStart = new DateOnly(2026, 4, 15),
                            SubscriptionId = 1
                        },
                        new
                        {
                            RenewalId = 2,
                            AmountPaid = 190.00m,
                            PaymentDate = new DateOnly(2026, 5, 14),
                            PeriodEnd = new DateOnly(2026, 6, 15),
                            PeriodStart = new DateOnly(2026, 5, 15),
                            SubscriptionId = 1
                        },
                        new
                        {
                            RenewalId = 3,
                            AmountPaid = 500.00m,
                            PaymentDate = new DateOnly(2026, 5, 1),
                            PeriodEnd = new DateOnly(2026, 6, 1),
                            PeriodStart = new DateOnly(2026, 5, 1),
                            SubscriptionId = 2
                        },
                        new
                        {
                            RenewalId = 4,
                            AmountPaid = 500.00m,
                            PaymentDate = new DateOnly(2026, 5, 30),
                            PeriodEnd = new DateOnly(2026, 7, 1),
                            PeriodStart = new DateOnly(2026, 6, 1),
                            SubscriptionId = 2
                        },
                        new
                        {
                            RenewalId = 5,
                            AmountPaid = 1125.00m,
                            PaymentDate = new DateOnly(2026, 6, 11),
                            PeriodEnd = new DateOnly(2026, 9, 11),
                            PeriodStart = new DateOnly(2026, 6, 11),
                            SubscriptionId = 3
                        },
                        new
                        {
                            RenewalId = 6,
                            AmountPaid = 300.00m,
                            PaymentDate = new DateOnly(2026, 5, 10),
                            PeriodEnd = new DateOnly(2026, 6, 10),
                            PeriodStart = new DateOnly(2026, 5, 10),
                            SubscriptionId = 4
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.CompanyClient", b =>
                {
                    b.HasBaseType("SystemUznawaniaPrzychodow.Entities.Client");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Krs")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasIndex("Krs")
                        .IsUnique()
                        .HasFilter("[Krs] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Company");

                    b.HasData(
                        new
                        {
                            ClientId = 2,
                            Address = "Kraków 30-002",
                            Email = "kontakt@softpol.pl",
                            PhoneNumber = "987654321",
                            CompanyName = "SoftPol Sp. z o.o.",
                            Krs = "0000123456"
                        },
                        new
                        {
                            ClientId = 4,
                            Address = "Wrocław 50-004",
                            Email = "office@megacorp.com",
                            PhoneNumber = "444333222",
                            CompanyName = "MegaCorp S.A.",
                            Krs = "0000987654"
                        },
                        new
                        {
                            ClientId = 6,
                            Address = "Łódź 90-006",
                            Email = "info@techsol.pl",
                            PhoneNumber = "111222333",
                            CompanyName = "TechSolutions",
                            Krs = "0000555444"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.IndividualClient", b =>
                {
                    b.HasBaseType("SystemUznawaniaPrzychodow.Entities.Client");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("[Pesel] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Individual");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            Address = "Warszawa 01-001",
                            Email = "jan.kowalski@gmail.com",
                            PhoneNumber = "123456789",
                            FirstName = "Jan",
                            IsDeleted = false,
                            LastName = "Kowalski",
                            Pesel = "12345678901"
                        },
                        new
                        {
                            ClientId = 3,
                            Address = "Gdańsk 80-003",
                            Email = "anna.nowak@eduplus.edu",
                            PhoneNumber = "555666777",
                            FirstName = "Anna",
                            IsDeleted = false,
                            LastName = "Nowak",
                            Pesel = "98765432109"
                        },
                        new
                        {
                            ClientId = 5,
                            Address = "Poznań 60-005",
                            Email = "p.zielinski@wp.pl",
                            PhoneNumber = "888777666",
                            FirstName = "Piotr",
                            IsDeleted = false,
                            LastName = "Zieliński",
                            Pesel = "55544433322"
                        });
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Contract", b =>
                {
                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Software", "Software")
                        .WithMany("Contracts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Discount", b =>
                {
                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Software", "Software")
                        .WithMany("Discounts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Payment", b =>
                {
                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Subscription", b =>
                {
                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Software", "Software")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.SubscriptionRenewal", b =>
                {
                    b.HasOne("SystemUznawaniaPrzychodow.Entities.Subscription", "Subscription")
                        .WithMany("Renewals")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Client", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Contract", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Software", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Discounts");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("SystemUznawaniaPrzychodow.Entities.Subscription", b =>
                {
                    b.Navigation("Renewals");
                });
#pragma warning restore 612, 618
        }
    }
}
